spring:
  application:
    name: BackendAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/content
    username: nexoc
    password: '0880'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: "Here is your actual email address"
    password: "Here is your actual password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8001

project:
  poster: content/

base:
  url: "http://localhost:8001"

cors:
  allowedOrigin: http://localhost:8080

